// /app/layout.js
import "./globals.css";
import "./style/global.scss"
import Layout from "./_common/layout/layout";

export const metadata = {
  title: "UZAQ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}